---
- name: Check if vms already exists
  community.libvirt.virt:
    command: list_vms
  register: all_vms

- name: Destroy {{ item }}
  ansible.builtin.shell: |
    virsh destroy {{ item }}
    virsh undefine --nvram --remove-all-storage {{ item }}
  when:
    - item is match("sno.*")
    - 'item in all_vms.list_vms'
  with_items: "{{ inventory_hostname_short }}"

- name: Remove sno tempfolders
  ansible.builtin.file:
    path: "{{ tempfolder }}/{{ item }}"
    state: absent
  with_items: "{{ inventory_hostname_short }}"

- name: Delete sno kubeconfig file locally if they exist
  delegate_to: localhost
  become: true
  become_user: michele
  ansible.builtin.file:
    path: "~/{{ item }}-kubeconfig"
    state: absent
  with_items: "{{ inventory_hostname_short }}"
