imageContentSources:
  - mirrors:
    - kuemper.int.rhx/ocp/openshift-release-dev
    source: quay.io/openshift-release-dev
  - mirrors:
    - kuemper.int.rhx/ocp/lvms4
    source: registry.redhat.io/lvms4
  - mirrors:
    - kuemper.int.rhx/ocp/openshift4
    source: registry.redhat.io/openshift4
  - mirrors:
    - kuemper.int.rhx/ocp/rhel8
    source: registry.redhat.io/rhel8
  - mirrors:
    - kuemper.int.rhx/ocp/openshift-gitops-1
    source: registry.redhat.io/openshift-gitops-1
  - mirrors:
    - kuemper.int.rhx/ocp/rh-sso-7
    source: registry.redhat.io/rh-sso-7
  - mirrors:
    - kuemper.int.rhx/ocp/rhacm2
    source: registry.redhat.io/rhacm2
  - mirrors:
    - kuemper.int.rhx/ocp/rhel9
    source: registry.redhat.io/rhel9
  - mirrors:
    - kuemper.int.rhx/ocp/multicluster-engine
    source: registry.redhat.io/multicluster-engine
  - mirrors:
    - kuemper.int.rhx/ocp/community-operator-pipeline-prod
    source: quay.io/community-operator-pipeline-prod
  - mirrors:
    - kuemper.int.rhx/ocp/kubebuilder
    source: gcr.io/kubebuilder
  - mirrors:
    - kuemper.int.rhx/ocp/hybridcloudpatterns
    source: quay.io/hybridcloudpatterns
  - mirrors:
    - kuemper.int.rhx/ocp/ubi8
    source: registry.redhat.io/ubi8
  - mirrors:
    - kuemper.int.rhx/ocp/ubi9
    source: registry.redhat.io/ubi9
