apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: test-fusion-access-operator
  namespace: openshift-marketplace
spec:
  displayName: Test Fusion Access for SAN Operator
  sourceType: grpc
  image: "kuemper.int.rhx/ocp/openshift-storage-scale/openshift-fusion-access-catalog:stable"
