---
apiVersion: scale.spectrum.ibm.com/v1beta1
kind: Filesystem
metadata:
  name: localfilesystem1
  namespace: ibm-spectrum-scale
  labels:
    scale.spectrum.ibm.com/allowDelete: ""
spec:
  local:
    blockSize: 4M
    pools:
    - name: system
      disks:
      - shareddisk1
    replication: 1-way
    type: shared
  seLinuxOptions:
    level: s0
    role: object_r
    type: container_file_t
    user: system_u
---
apiVersion: scale.spectrum.ibm.com/v1beta1
kind: Filesystem
metadata:
  name: localfilesystem2
  namespace: ibm-spectrum-scale
  labels:
    scale.spectrum.ibm.com/allowDelete: ""
spec:
  local:
    blockSize: 4M
    pools:
    - name: system
      disks:
      - shareddisk2
    replication: 1-way
    type: shared
  seLinuxOptions:
    level: s0
    role: object_r
    type: container_file_t
    user: system_u
