apiVersion: scale.spectrum.ibm.com/v1beta1
kind: LocalDisk
metadata:
  name: shareddisk1
  namespace: ibm-spectrum-scale
spec:
  device: /dev/disk/by-id/dm-uuid-mpath-{{ multipath_ids[0] }}
  node: worker-0.cluster.ocplab.ocp
  # nodeConnectionSelector defines the nodes that have the shared lun directly attached to them
  nodeConnectionSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/worker
      operator: Exists

  # set below only during testing
  existingDataSkipVerify: true
---
apiVersion: scale.spectrum.ibm.com/v1beta1
kind: LocalDisk
metadata:
  name: shareddisk2
  namespace: ibm-spectrum-scale
spec:
  device: /dev/disk/by-id/dm-uuid-mpath-{{ multipath_ids[1] }}
  node: worker-0.cluster.ocplab.ocp
  # nodeConnectionSelector defines the nodes that have the shared lun directly attached to them
  nodeConnectionSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/worker
      operator: Exists

  # set below only during testing
  existingDataSkipVerify: true
