{% if fusion_ga %}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-fusion-access-operator
  namespace: ibm-fusion-access
spec:
  channel: stable-v1
  installPlanApproval: Automatic
  name: openshift-fusion-access-operator
  source: cs-certified-operator-index-v{{ ocp_maj_min_version_dashed }}
  sourceNamespace: openshift-marketplace
{% else %}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-fusion-access-operator
  namespace: ibm-fusion-access
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: openshift-fusion-access-operator
  source: test-fusion-access-operator
  sourceNamespace: openshift-marketplace
{% endif %}
