kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    channels:
    - name: stable-4.18
      type: ocp
    - name: stable-4.17
      type: ocp
    graph: true
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.18
    packages:
      - name: kubernetes-nmstate-operator
      - name: lvms-operator
      - name: local-storage-operator
      - name: kubevirt-hyperconverged
      - name: advanced-cluster-management
        channels:
          - name: release-2.12
      - name: multicluster-engine
        channels:
          - name: stable-2.6
      - name: openshift-gitops-operator
        channels:
          - name: gitops-1.15
  - catalog: registry.redhat.io/redhat/community-operator-index:v4.18
    packages:
      - name: patterns-operator
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.17
    packages:
      - name: lvms-operator
      - name: kubernetes-nmstate-operator
      - name: local-storage-operator
      - name: kubevirt-hyperconverged
      - name: advanced-cluster-management
        channels:
          - name: release-2.12
      - name: multicluster-engine
        channels:
          - name: stable-2.6
      - name: openshift-gitops-operator
        channels:
          - name: gitops-1.15
  - catalog: registry.redhat.io/redhat/community-operator-index:v4.17
    packages:
      - name: patterns-operator
  additionalImages:
  - name: registry.redhat.io/ubi8/ubi:latest
  - name: registry.redhat.io/ubi9/ubi:latest
  - name: registry.redhat.io/ubi9/ubi-minimal:latest
  - name: registry.connect.redhat.com/hashicorp/vault:1.17.6-ubi
  - name: registry.access.redhat.com/ubi8/httpd-24:1-226
  - name: ghcr.io/external-secrets/external-secrets:v0.10.2-ubi
  - name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel9:latest
  - name: quay.io/hybridcloudpatterns/acm:0.1.6
  - name: quay.io/hybridcloudpatterns/clustergroup:0.9.16
  - name: quay.io/hybridcloudpatterns/gitea:0.0.3
  - name: quay.io/hybridcloudpatterns/golang-external-secrets:0.1.4
  - name: quay.io/hybridcloudpatterns/hashicorp-vault:0.1.5
  - name: quay.io/hybridcloudpatterns/utility-container:latest
  - name: quay.io/hybridcloudpatterns/imperative-container:v1
  - name: quay.io/hybridcloudpatterns/pattern-install:0.0.7
  - name: docker.io/gitea/gitea:1.22.6-rootless
  - name: quay.io/openshift-storage-scale/openshift-storage-scale-operator:0.0.5
  - name: quay.io/openshift-storage-scale/openshift-storage-scale-bundle:0.0.5
  - name: quay.io/openshift-storage-scale/openshift-storage-scale-catalog:0.0.5
  - name: quay.io/openshift-storage-scale/openshift-storage-scale-console:0.0.5
  - name: quay.io/openshift-storage-scale/openshift-storage-scale-diskmaker:0.0.5
  - name: quay.io/openshift-storage-scale/openshift-storage-scale-diskmaker:latest
  - name: quay.io/openshift/origin-kube-rbac-proxy:latest
  - name: gcr.io/kubebuilder/kube-rbac-proxy:v0.16.0
  - name: quay.io/containerdisks/centos-stream:9
  - name: quay.io/containerdisks/centos-stream:10
  - name: quay.io/containerdisks/fedora:latest
  # v5.2.2.0
  - name: quay.io/rhsysdeseng/cpopen/ibm-spectrum-scale-csi-operator@sha256:c292fa07a03f5accac554a5f366b7241c31dbb85fc4617c0fe2428cf103fce56
  - name: quay.io/rhsysdeseng/cpopen/ibm-spectrum-scale-must-gather@sha256:8d6561114d9d4161eaab4529b7664ab32b032654763662dd79054540766da0f7
  - name: quay.io/rhsysdeseng/cpopen/ibm-spectrum-scale-operator@sha256:1580665f94e133f591e27cb5a3237652b7d0c5a31848457d2a2fad4b356aa530
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/csi/csi-attacher@sha256:b4d611100ece2f9bc980d1cb19c2285b8868da261e3b1ee8f45448ab5512ab94
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/csi/csi-node-driver-registrar@sha256:e01facb9fb9cffaf52d0053bdb979fbd8c505c8e411939a6e026dd061a6b4fbe
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/csi/csi-provisioner@sha256:7b9cdb5830d01bda96111b4f138dbddcc01eed2f95aa980a404c45a042d60a10
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/csi/csi-resizer@sha256:be6a7de1d43dba90710b61bd3d0d8f568654a6adadaeea9188cf4cd3554cbb87
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/csi/csi-snapshotter@sha256:b3e90b33781670ac050c22c9e88b9e876493dca248966b9da6f7a90cc412ab86
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/csi/ibm-spectrum-scale-csi-driver@sha256:6cf6a3818f48c2bcb5460c4902c5d44ad73c415a5f2980a374062a4bb18840ea
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/csi/livenessprobe@sha256:33692aed26aaf105b4d6e66280cceca9e0463f500c81b5d8c955428a75438f32
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/data-access/ibm-spectrum-scale-daemon@sha256:82ff198432997b628213f8c828b4843019f4a163e608eee8773e9e85686144bd
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/data-management/ibm-spectrum-scale-daemon@sha256:1f7a9a48f15162749e2a399b83f704beb73bb9fffd93275b0b0651ddca6dd83b
  # - name: quay.io/rhsysdeseng/cp/spectrum/scale/erasure-code/ibm-spectrum-scale-daemon@sha256:2fdc55402b241c09c17f9b3a4ecc4008d258e4eb19ebdeb1177d975b493ee6df
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/ibm-spectrum-scale-coredns@sha256:88cbfe40fd302a6467cb7e852b298f6c8d8659782ab313706d491d3ddf172a6e
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/ibm-spectrum-scale-core-init@sha256:ee984f59941faa674af7450f39d52df3409d3dedb5b930fa0e33b310c9dd6de1
  # - name: quay.io/rhsysdeseng/cp/spectrum/scale/ibm-spectrum-scale-ganesha@sha256:04e5e5188febe046c9d6f3cdf6f06e1c92d62088caa50fb65948b73be3dc4dda
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/ibm-spectrum-scale-grafana-bridge@sha256:a8f5e13168e4c9d15a3026cdec5dde98a75ddf2a17c6bea4fc67b32e825e2632
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/ibm-spectrum-scale-gui@sha256:a5b65cb784e84acc80f7318ca30a03d270b7931e500fb0bcece87c6adcf4cd56
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/ibm-spectrum-scale-logs@sha256:88e1ab0b4b93e5730bdc5657d0fdbc593d814392321005378d7a87b013cdc86a
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/ibm-spectrum-scale-monitor@sha256:cc6d431ea461b58faceb759e8d23cd66554a1dd4c057d6ca9c56aaaecd8d8757
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/ibm-spectrum-scale-pmcollector@sha256:1dd8b31e3a44f10597206945ee4ee580ea5e325f7e9e69972daef24c10f399ae
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/ibm-spectrum-scale-pmsensors@sha256:dc57f960aa63b3bc24c94a065b0747548d0895cd081ec86dcb2714b69ee8a265
  # - name: quay.io/rhsysdeseng/cp/spectrum/scale/ibm-spectrum-scale-stunnel@sha256:b900b3912f7ba3e26e6d99c8f5dab66c2de23ed9fe2cf0ab79bae21515676ed0
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/postgres@sha256:bbd7346fab25b7e0b25f214829d6ebfb78ef0465059492e46dee740ce8fcd844
  # v5.2.2.1
  # - name: quay.io/rhsysdeseng/cp/spectrum/scale/erasure-code/ibm-spectrum-scale-daemon@sha256:6e2bfb235a2c89317496124a6f37ad26516530bdc03600b591bd9c846ec92f72
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/data-management/ibm-spectrum-scale-daemon@sha256:72868067f337d18f4f61797693e403db177f8e28c7be682ed5c514636fef0f3a
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/data-access/ibm-spectrum-scale-daemon@sha256:814bda6320cfe94eafefa331e4e30f4e07fc16fc0183067bfffada5d731a32e3
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/ibm-spectrum-scale-core-init@sha256:fde69d67fddd2e4e0b7d7d85387a221359daf332d135c9b9f239fb31b9b82fe0
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/ibm-spectrum-scale-gui@sha256:11ffb0e5bccf6d679c86e02ed7d1df155800c6502adb72378e08c007ddd66443
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/postgres@sha256:0bcc5bbbb2aa9c9b4c6505845918c7eb55d783cf5c1f434fac33012579fb149d
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/ibm-spectrum-scale-logs@sha256:9828aa1de297e1e37f24bbdd1870149d50ebc2ac78089c6be12bb6934e080143
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/ibm-spectrum-scale-pmcollector@sha256:3278937eafb9d1eeb75f9dbae5b12e449fd180f4502acf3989771565f6aac794
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/ibm-spectrum-scale-monitor@sha256:898dc2ad37073f3793562a4d4af90e0a399c92f612de1de6bff15b753f587f32
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/ibm-spectrum-scale-grafana-bridge@sha256:956a98023ae3a877410c922c006080ecc7f825eca273fa5dd2bdb94873d1f725
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/ibm-spectrum-scale-coredns@sha256:6a317b23fee629c0b07eb95d34ab7593bb38d41bffc5d1cd4cb2870539c66cd4
  - name: quay.io/rhsysdeseng/cpopen/ibm-spectrum-scale-must-gather@sha256:614cc54f7ed246aef270ef5532aaa32bb64b7c6024e85b562d7ea8675f750192
  # - name: quay.io/rhsysdeseng/cp/spectrum/scale/ibm-spectrum-scale-ganesha@sha256:43c2f4306100419eca3706b080f49cfce13830e9982fd50dd0ea6c050dc9b07a
  # - name: quay.io/rhsysdeseng/cp/spectrum/scale/ibm-spectrum-scale-stunnel@sha256:a12592525a1d0d67755f2bd0e23cb81c2c99cbb3113366ba27e92a2f9f72130d
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/ibm-spectrum-scale-pmsensors@sha256:8cbcc426c8ed0237b988e20b5f8ea235dae617bef2fcaaac1d34fdb5fc2d6020
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/csi/csi-snapshotter@sha256:b3e90b33781670ac050c22c9e88b9e876493dca248966b9da6f7a90cc412ab86
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/csi/csi-attacher@sha256:b4d611100ece2f9bc980d1cb19c2285b8868da261e3b1ee8f45448ab5512ab94
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/csi/csi-provisioner@sha256:7b9cdb5830d01bda96111b4f138dbddcc01eed2f95aa980a404c45a042d60a10
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/csi/livenessprobe@sha256:33692aed26aaf105b4d6e66280cceca9e0463f500c81b5d8c955428a75438f32
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/csi/csi-node-driver-registrar@sha256:e01facb9fb9cffaf52d0053bdb979fbd8c505c8e411939a6e026dd061a6b4fbe
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/csi/csi-resizer@sha256:be6a7de1d43dba90710b61bd3d0d8f568654a6adadaeea9188cf4cd3554cbb87
  - name: quay.io/rhsysdeseng/cp/spectrum/scale/csi/ibm-spectrum-scale-csi-driver@sha256:ffecac38546bf0b36e0c87fd6e4c06c58bc85c6f7c2140651149a284d29a5d6f
  - name: quay.io/rhsysdeseng/cpopen/ibm-spectrum-scale-csi-operator@sha256:a371ac2539ddf2e4708ba22f539381880e500758de20e8db3823b1f32c5a3794
  - name: quay.io/rhsysdeseng/cpopen/ibm-spectrum-scale-operator@sha256:ceb5c5cf5fd94cc8a677154c31cb8b814c53a8fcd4dfcec0ba2951f73bf9a542
