kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
    imageURL: fw.int.rhx/ocp
    skipTLS: false
mirror:
  platform:
    channels:
    - name: stable-4.15
      type: ocp
    - name: stable-4.14
      type: ocp
    graph: true
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.15
    #full: true
    packages:
      - name: lvms-operator
      - name: advanced-cluster-management
      - name: multicluster-engine
      - name: openshift-gitops-operator
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.14
    #full: true
    packages:
      - name: lvms-operator
      - name: advanced-cluster-management
      - name: multicluster-engine
      - name: openshift-gitops-operator
  - catalog: registry.redhat.io/redhat/community-operator-index:v4.15
    packages:
      - name: patterns-operator
  - catalog: registry.redhat.io/redhat/community-operator-index:v4.14
    packages:
      - name: patterns-operator
    #registry.redhat.io/redhat/redhat-marketplace-index:v4.14
    #registry.redhat.io/redhat/certified-operator-index:v4.14
  additionalImages:
  - name: registry.redhat.io/ubi8/ubi:latest
  - name: registry.redhat.io/ubi9/ubi:latest
  helm: {}
