kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    channels:
    - name: stable-4.18
      type: ocp
    - name: stable-4.17
      type: ocp
    graph: true
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.18
    packages:
      - name: lvms-operator
      - name: local-storage-operator
      - name: advanced-cluster-management
        channels:
          - name: release-2.12
      - name: multicluster-engine
        channels:
          - name: stable-2.6
      - name: openshift-gitops-operator
        channels:
          - name: gitops-1.15
  - catalog: registry.redhat.io/redhat/community-operator-index:v4.18
    packages:
      - name: patterns-operator
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.17
    packages:
      - name: lvms-operator
      - name: local-storage-operator
      - name: advanced-cluster-management
        channels:
          - name: release-2.12
      - name: multicluster-engine
        channels:
          - name: stable-2.6
      - name: openshift-gitops-operator
        channels:
          - name: gitops-1.15
  - catalog: registry.redhat.io/redhat/community-operator-index:v4.17
    packages:
      - name: patterns-operator
  additionalImages:
  - name: registry.redhat.io/ubi8/ubi:latest
  - name: registry.redhat.io/ubi9/ubi:latest
  - name: registry.redhat.io/ubi9/ubi-minimal:latest
  - name: registry.connect.redhat.com/hashicorp/vault:1.17.6-ubi
  - name: registry.access.redhat.com/ubi8/httpd-24:1-226
  - name: ghcr.io/external-secrets/external-secrets:v0.10.2-ubi
  - name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel9:latest
  - name: quay.io/hybridcloudpatterns/acm:0.1.6
  - name: quay.io/hybridcloudpatterns/clustergroup:0.9.16
  - name: quay.io/hybridcloudpatterns/gitea:0.0.3
  - name: quay.io/hybridcloudpatterns/golang-external-secrets:0.1.4
  - name: quay.io/hybridcloudpatterns/hashicorp-vault:0.1.5
  - name: quay.io/hybridcloudpatterns/utility-container:latest
  - name: quay.io/hybridcloudpatterns/imperative-container:v1
  - name: quay.io/hybridcloudpatterns/pattern-install:0.0.7
  - name: docker.io/gitea/gitea:1.22.6-rootless
  - name: quay.io/hybridcloudpatterns/purple-storage-rh-operator:0.0.3
  - name: quay.io/hybridcloudpatterns/purple-storage-rh-operator-bundle:v0.0.3
  - name: quay.io/hybridcloudpatterns/purple-storage-rh-operator-catalog:v0.0.3
