kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    channels:
    - name: stable-4.16
      type: ocp
    # - name: stable-4.15
    #   type: ocp
    graph: true
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.16
    # All bundles of all channels of the specified catalog
    # full: true
    packages:
      - name: lvms-operator
      - name: advanced-cluster-management
        channels:
          - name: release-2.10
      - name: multicluster-engine
        channels:
          - name: stable-2.5
      - name: openshift-gitops-operator
        channels:
          - name: gitops-1.12
          - name: gitops-1.13
      #minVersion: 1.12.0
      #maxVersion: 1.13.1
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.15
    # All bundles of all channels of the specified catalog
    # full: true
    packages:
      - name: lvms-operator
      - name: advanced-cluster-management
        channels:
          - name: release-2.10
      - name: multicluster-engine
      - name: openshift-gitops-operator
        channels:
          - name: gitops-1.12
          - name: gitops-1.13
  - catalog: registry.redhat.io/redhat/community-operator-index:v4.16
    packages:
      - name: patterns-operator
  - catalog: registry.redhat.io/redhat/community-operator-index:v4.15
    packages:
      - name: patterns-operator
  #   #registry.redhat.io/redhat/redhat-marketplace-index:v4.14
  #   #registry.redhat.io/redhat/certified-operator-index:v4.14
  additionalImages:
  - name: registry.redhat.io/ubi8/ubi:latest
  - name: registry.redhat.io/ubi9/ubi:latest
  - name: quay.io/ansible/creator-ee:latest
  - name: registry.connect.redhat.com/hashicorp/vault:1.17.2-ubi
  - name: registry.access.redhat.com/ubi8/httpd-24:1-226
  - name: ghcr.io/external-secrets/external-secrets:v0.9.20-ubi
  - name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel9:latest
