---
apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "local-disks"
  namespace: "openshift-local-storage"
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker-0.cluster.ocplab.ocp
          - worker-1.cluster.ocplab.ocp
          - worker-2.cluster.ocplab.ocp
          - worker-3.cluster.ocplab.ocp
  storageClassDevices:
    - storageClassName: "localfs-sc"
      volumeMode: Filesystem
      fsType: xfs
      devicePaths:
        - /dev/disk/by-id/scsi-SQEMU_QEMU_HARDDISK_seconddisk
