---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
  name: openshift-local-storage
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-local-storage-operatorgroup
  namespace: openshift-local-storage
spec:
  targetNamespaces:
  - openshift-local-storage
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: local-storage
  namespace: openshift-local-storage
spec:
  installPlanApproval: Automatic
  name:  local-storage-operator
  channel: stable
{% if enable_disconnected %}
  source: "cs-redhat-operator-index-v{{ ocp_maj_min_version_dashed }}"
{% else %}
  source: "redhat-operators"
{% endif %}
  sourceNamespace: openshift-marketplace
