apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: {{ iscsi_mco_pool }}
  name: 99-{{ iscsi_mco_pool }}-iscsi
spec:
  extensions:
    - kernel-devel
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      # - contents:
      #     source: data:text/plain;charset=utf-8;base64,{{ iscsi_multipath_conf | b64encode }}
      #   filesystem: root
      #   mode: 420
      #   path: /etc/multipath.conf
      - contents:
          source: data:text/plain;charset=utf-8;base64,b3B0aW9ucyBrdm1faW50ZWwgbmVzdGVkPTEKb3B0aW9ucyBrdm1fYW1kIG5lc3RlZD0xCg==
        filesystem: root
        mode: 420
        path: /etc/modprobe.d/kvm.conf
      - contents:
          source: data:text/plain;charset=utf-8;base64,{{ iscsi_login_script | b64encode }}
        filesystem: root
        mode: 493
        path: /usr/local/sbin/iscsi-login
    systemd:
      units:
      - contents: |
          [Unit]
          Description=Custom CoreOS Generate iSCSI Initiator Name
          Before=coreos-generate-iscsi-initiatorname.service
          Before=iscsid.service

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/sh -c 'echo "InitiatorName=`hostname`" > /etc/iscsi/initiatorname.iscsi'
          RemainAfterExit=yes

          [Install]
          WantedBy=multi-user.target
        enabled: true
        name: custom-coreos-generate-iscsi-initiatorname.service
      - contents: |
          [Unit]
          Description=Logs into the iSCSI target if not already loged
          Before=kubelet.service
          After=iscsi.service iscsid.service

          [Service]
          Type=oneshot
          RemainAfterExit=no
          User=root
          ExecStart=/usr/local/sbin/iscsi-login

          TimeoutSec=300

          [Install]
          WantedBy=multi-user.target
        enabled: true
        name: "iscsi-login-target.service"
      - name: iscsid.service
        enabled: true
      - name: iscsi.service
        enabled: true
      # - name: multipathd.service
      #   enabled: true
