---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-nmstate
spec:
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kubernetes-nmstate-operator
  namespace: openshift-nmstate
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kubernetes-nmstate-operator
  source: cs-redhat-operator-index-v{{ ocp_maj_min_version_dashed }}
  sourceNamespace: openshift-marketplace
  startingCSV: kubernetes-nmstate-operator.4.17.0-202502250404
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kubernetes-nmstate-operator
  namespace: openshift-nmstate
spec:
  upgradeStrategy: Default
  targetNamespaces:
    - openshift-nmstate

