apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: purple-storage-rh-operator
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: purple-storage-rh-operator
  source: test-purplestorage-operator
  sourceNamespace: openshift-marketplace
