---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ secret_name }}
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: {{ gitrepo }}
  username: dontcare
  password: {{ github_pat }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ argo_ns }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ secret_name }}
  namespace: {{ argo_ns }}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: {{ gitrepo }}
  username: dontcare
  password: {{ github_pat }}
