---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-update-service
spec:
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: update-service-operatorgroup
  namespace: openshift-update-service
spec:
  # upgradeStrategy: Default
  targetNamespaces:
  - openshift-update-service
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cincinnati-operator
  namespace: openshift-update-service
spec:
  channel: v1
  name: cincinnati-operator
  source: cs-redhat-operator-index-v{{ ocp_maj_min_version_dashed }}
  sourceNamespace: openshift-marketplace
