---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cnv
spec:
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kubevirt-hyperconverged
  source: cs-redhat-operator-index-v{{ ocp_maj_min_version_dashed }}
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cnv-operator
  namespace: openshift-cnv
spec:
  upgradeStrategy: Default
  targetNamespaces:
    - openshift-cnv
