---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
  labels:
    vm.kubevirt.io/template: rhel8-server-tiny
    vm.kubevirt.io/template.revision: "45"
    vm.kubevirt.io/template.version: v0.11.3
  name: test-vm
  namespace: ibm-test-deployment
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: vm-test-dv
    spec:
      sourceRef:
        kind: DataSource
        name: vm-test-dv
        namespace: ibm-test-deployment
      pvc:
        accessModes:
          - "ReadWriteMany"
        resources:
          requests:
            storage: "5Gi"
        storageClassName: ibm-spectrum-scale-fs1
        volumeMode: Filesystem
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: tiny
        vm.kubevirt.io/os: rhel8
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: test-vm
        kubevirt.io/size: tiny
        vm.kubevirt.io/name: test-vm
    spec:
      # accessCredentials:
      #   - sshPublicKey:
      #       propagationMethod:
      #         configDrive: {}
      #       source:
      #         secret:
      #           secretName: authorizedsshkeys-test-vm
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: test-vm
          - disk:
              bus: virtio
            name: cloudinitdisk
          inputs:
          - bus: virtio
            name: tablet
            type: tablet
          interfaces:
          - masquerade: {}
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: pc-q35-rhel8.4.0
        resources:
          requests:
            memory: 1Gi
      evictionStrategy: LiveMigrate
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: vm-test-dv
        name: test-vm
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: kni
            password: redhat
            chpasswd: { expire: False }
            ssh_authorized_keys:
              - {{ sshkey2 }}
            runcmd:
            - echo "Hello from `hostname`" |sudo tee /tmp/washere
        name: cloudinitdisk        
---
apiVersion: v1
kind: Service
metadata:
  name: vm-port
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22
  selector:
    vm.kubevirt.io/name: test-vm
  sessionAffinity: None
  type: NodePort
