---
- name: Importing ACM clusters automatically
  hosts: localhost
  connection: local
  pre_tasks:
    - name: Set VP_HUBCONFIG and VP_SPOKECONFIG facts from env variables
      ansible.builtin.set_fact:
        VP_HUBCONFIG: "{{ lookup('env', 'VP_HUBCONFIG') }}"
        VP_SPOKECONFIG: "{{ lookup('env', 'VP_SPOKECONFIG') }}"

    - name: Check for correct VP_HUBCONFIG env variable
      ansible.builtin.fail:
        msg: "VP_HUBCONFIG env variable needs to be set and pointing to the HUB kubeconfig file"
      when:
        VP_HUBCONFIG is not defined or VP_HUBCONFIG | length == 0

    - name: Check for correct VP_SPOKECONFIG env variable
      ansible.builtin.fail:
        msg: "VP_SPOKECONFIG env variable needs to be set and pointing to the REGION kubeconfig file"
      when:
        VP_SPOKECONFIG is not defined or VP_SPOKECONFIG | length == 0

    - name: Print the hub and regional kubeconfigs
      ansible.builtin.debug:
        msg: "VP_HUBCONFIG: {{ VP_HUBCONFIG }} - VP_SPOKECONFIG: {{ VP_SPOKECONFIG }}"

  roles:
    - acm_import
