---
- name: Install AGOF on two rhel boxes
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  become_user: michele
  vars:
    agoftempfolder: "~/agof"
    gitrepo: https://github.com/validatedpatterns/agof
    gitbranch: main
    inventory: ~/inventory_agof
  tasks:
    - name: Delete temporary folder
      ansible.builtin.file:
        path: "{{ agoftempfolder }}"
        state: absent

    - name: Create temporary folder
      ansible.builtin.file:
        path: "{{ agoftempfolder }}/agof"
        state: directory
        recurse: true

    - name: Clone git repo
      ansible.builtin.git:
        repo: "{{ gitrepo }}"
        version: "{{ gitbranch }}"
        dest: "{{ agoftempfolder }}/agof"
        clone: true

    - name: Template agof inventory
      ansible.builtin.template:
        src: ../templates/inventory_agof.j2
        dest: ~/inventory_agof

    - name: Template agof vault
      ansible.builtin.template:
        src: ../templates/agof_vault.yml.j2
        dest: ~/agof_vault.yml

    - name: Install AGOF
      ansible.builtin.shell: |
        set -e -o pipefail
        ./pattern.sh make from_os_install INVENTORY="{{ inventory }}"
      args:
        chdir: "{{ agoftempfolder }}/agof"
