---
- name: Set firewall rules
  hosts: fw
  gather_facts: false
  become: true
  tasks:
    - name: Set rules to REJECT for SNOS
      ansible.builtin.lineinfile:
        path: /etc/shorewall/rules
        regexp: '^.*lab:{{ clusters[item].ip }}.*web$'
        line: "REJECT         lab:{{ clusters[item].ip }}              web"
        owner: root
        group: root
        mode: "0600"
      when: enable_disconnected
      with_items: "{{ snos | default('snohosts') }}"

    - name: Set rules to ALLOW for SNOS
      ansible.builtin.lineinfile:
        path: /etc/shorewall/rules
        regexp: '^.*lab:{{ clusters[item].ip }}.*web$'
        line: "ACCEPT         lab:{{ clusters[item].ip }}              web"
        owner: root
        group: root
        mode: "0600"
      when: not enable_disconnected
      with_items: "{{ snos | default('snohosts') }}"

    - name: Restart shorewall
      ansible.builtin.systemd:
        name: shorewall
        state: restarted

- name: Setup nginx on kuemper
  hosts: kvm:
  gather_facts: false
  become: true
  tasks:
    ansible.builtin.template:
      src: "templates/nginx_conf.j2"
      dest: /tmp/nginx.conf

- name: Install full cluster
  hosts: "{{ snos | default('snohosts') }}"
  gather_facts: false
  become: true
  strategy: ansible.builtin.free
  roles:
    - full_cluster
