---
- name: Install full cluster
  hosts: kvm
  gather_facts: false
  become: true
  tasks:
    - name: Remove full cluster folder
      ansible.builtin.file:
        path: "{{ fullclusterfolder }}"
        state: absent

    - name: Create full cluster config folder
      ansible.builtin.file:
        path: "{{ fullclusterfolder }}"
        state: directory
        recurse: true

    - name: Prepare install-config.yaml for full cluster debugging
      ansible.builtin.template:
        src: ../templates/full-cluster-install-config.j2.yaml
        dest: "{{ tempfolder }}/full-cluster-install-config.yaml"
        mode: "0640"

    - name: Prepare install-config.yaml for full cluster
      ansible.builtin.template:
        src: ../templates/full-cluster-install-config.j2.yaml
        dest: "{{ fullclusterfolder }}/install-config.yaml"
        mode: "0640"

    - name: Create full cluster manifests
      ansible.builtin.command: |
        "{{ mirrorfolder }}/{{ ocp_version }}/openshift-install" create manifests --dir=.
      args:
        chdir: "{{ fullclusterfolder }}"

    - name: Create full cluster ignition configs
      ansible.builtin.command: |
        "{{ mirrorfolder }}/{{ ocp_version }}/openshift-install" create ignition-configs --dir=.
      args:
        chdir: "{{ fullclusterfolder }}"

    - name: Make all files readable
      ansible.builtin.file:
        path: "{{ fullclusterfolder }}"
        mode: u=rwX,g=rX,o=rX
        recurse: true

    - name: Run coreos ignition embedding for bootstrap node
      ansible.builtin.shell: |
        set -xe -o pipefail
        cp {{ mirrorfolder }}/{{ ocp_version }}/rhcos-live.iso "{{ fullclusterfolder }}/{{ item }}-rhcos-live.iso"
        export IGNITION=$(echo "{{ item }}" | sed -e 's/-.*$//')
        echo "${IGNITION}"
        podman run --privileged --pull always --rm \
            -v /dev:/dev -v /run/udev:/run/udev -v "{{ fullclusterfolder }}:/data" \
            -w /data quay.io/coreos/coreos-installer:release \
            iso customize "{{ item }}-rhcos-live.iso" --dest-ignition "${IGNITION}".ign \
            --dest-device "/dev/disk/by-id/wwn-{{ full_cluster[item].wwn }}"
      args:
        chdir: "{{ tempfolder }}"
      register: test
      with_items:
        - bootstrap
        - master-0
        - master-1
        - master-2
        - worker-0
        - worker-1
        - worker-2
        - worker-3

    - name: "Create bootstrap VM"
      ansible.builtin.command: >-
        virt-install
        --name {{ item }}
        --hvm
        --virt-type kvm
        --arch {{ arch }}
        --cdrom {{ fullclusterfolder }}/{{ item }}-rhcos-live.iso
        --os-variant rhel8.0
        --network bridge="{{ bridge_interface }}",mac="{{ mac_prefix }}:{{ full_cluster[item].mac_nr }}"
        --vcpus {{ full_cluster[item].cpus }}
        --ram {{ full_cluster[item].ram }}
        --disk pool={{ rhel_pool }},size={{ full_cluster[item].disk }},format=qcow2,bus=scsi,cache={{ full_cluster[item].cache }},wwn={{ full_cluster[item].wwn }}
        --disk pool={{ rhel_pool }},size={{ full_cluster[item].disk2 }},format=qcow2,bus=scsi,cache={{ full_cluster[item].cache2 }},wwn={{ full_cluster[item].wwn2 }},serial={{ diskserial }}
        --check disk_size=off
        --graphics spice,listen=127.0.0.1
        --noautoconsole
      with_items:
        - bootstrap
        - master-0
        - master-1
        - master-2
        - worker-0
        - worker-1
        - worker-2
        - worker-3
      retries: 0
      delay: 10
      register: vm_creation
      until: vm_creation is not failed

    - name: Remove ISOs
      ansible.builtin.shell: |
        set -e
        rm -f "{{ item }}-live.iso"
      args:
        chdir: "{{ tempfolder }}"
      with_items:
        - bootstrap
        - master-0
        - master-1
        - master-2
        - worker-0
        - worker-1
        - worker-2
        - worker-3

    - name: Wait for vm to be stopped
      ansible.builtin.shell: |
        set -e -o pipefail
        virsh list --all | grep -w "{{ item }}" | grep -v running
      register: running
      retries: 100
      delay: 20
      until: running is not failed
      with_items:
        - bootstrap
        - master-0
        - master-1
        - master-2
        - worker-0
        - worker-1
        - worker-2
        - worker-3

    - name: Start "{{ item }}"
      ansible.builtin.command: |
        virsh start "{{ item }}"
      with_items:
        - bootstrap
        - master-0
        - master-1
        - master-2
        - worker-0
        - worker-1
        - worker-2
        - worker-3
      retries: 3
      delay: 10
      register: restart
      until: restart is not failed

    - name: Wait for bootstrap process to complete
      ansible.builtin.command: |
        "{{ mirrorfolder }}/{{ ocp_version }}/openshift-install" --dir=. wait-for bootstrap-complete --log-level=info
      args:
        chdir: "{{ fullclusterfolder }}"

    - name: Check if vms already exists
      community.libvirt.virt:
        command: list_vms
      register: all_vms

    - name: Destroy {{ item }}
      ansible.builtin.shell: |
        virsh destroy {{ item }}
        virsh undefine --nvram --remove-all-storage {{ item }}
      when: 'item in all_vms.list_vms'
      with_items:
       - bootstrap

    - name: Fetch kubeconfig file
      ansible.posix.synchronize:
        mode: pull
        src: "{{ tempfolder }}/fullcluster/auth/kubeconfig"
        dest: "~/fullcluster-kubeconfig"

    - name: Fix permissions
      ansible.builtin.shell: |
        chmod 0600 "/home/michele/fullcluster-kubeconfig"
      delegate_to: localhost

    - name: Wait for installation completion
      ansible.builtin.shell: |
        set -e -o pipefail
        "{{ mirrorfolder }}/{{ ocp_version }}/openshift-install" --dir=. wait-for install-complete --log-level=info
      args:
        chdir: "{{ fullclusterfolder }}"

    - name: Approve all machines until we have four workers
      ansible.builtin.shell: |
        set -e -o pipefail
        export KUBECONFIG="{{ tempfolder }}/fullcluster/auth/kubeconfig"
        COUNT=$(oc get nodes -l "node-role.kubernetes.io/worker" --no-headers)
        if [ ${COUNT} -eq 4 ]; then
            exit 0
        fi
        "{{ mirrorfolder }}/{{ ocp_version }}"/oc get csr -o {% raw %}go-template='{{range .items}}{{if not .status}}{{.metadata.name}}{{"\n"}}{{end}}{{end}}{% endraw %}' | xargs --no-run-if-empty oc adm certificate approve
      register: csr
      until: csr is not failed
      retries: 25
      delay: 10


    - name: Approve all machines again
      ansible.builtin.shell: |
        set -e -o pipefail
        export KUBECONFIG="{{ tempfolder }}/fullcluster/auth/kubeconfig"
        "{{ mirrorfolder }}/{{ ocp_version }}"/oc get csr -o {% raw %}go-template='{{range .items}}{{if not .status}}{{.metadata.name}}{{"\n"}}{{end}}{{end}}{% endraw %}' | xargs --no-run-if-empty oc adm certificate approve
        sleep 10
        "{{ mirrorfolder }}/{{ ocp_version }}"/oc get csr -o {% raw %}go-template='{{range .items}}{{if not .status}}{{.metadata.name}}{{"\n"}}{{end}}{{end}}{% endraw %}' | xargs --no-run-if-empty oc adm certificate approve
      register: csr
      until: csr is not failed
      retries: 5
      delay: 10

    - name: Apply mirroring yaml files
      ansible.builtin.shell: |
        set -e -o pipefail
        export KUBECONFIG="{{ tempfolder }}/fullcluster/auth/kubeconfig"
        "{{ mirrorfolder }}/{{ ocp_version }}"/oc apply -f "{{ local_mirror }}/workspace/working-dir/cluster-resources/*oc-mirror.yaml"
        "{{ mirrorfolder }}/{{ ocp_version }}"/oc apply -f "{{ local_mirror }}/workspace/working-dir/cluster-resources/cs-*index*v{{ ocp_maj_min_version_dashed }}.yaml"
      when: enable_disconnected
      register: mirroring
      until: mirroring is not failed
      retries: 50
      delay: 30

    - name: Disable default catalog sources
      ansible.builtin.shell: |
        set -e -o pipefail
        export KUBECONFIG="{{ tempfolder }}/fullcluster/auth/kubeconfig"
        "{{ mirrorfolder }}/{{ ocp_version }}"/oc patch OperatorHub cluster --type json -p '[{"op": "add", "path": "/spec/disableAllDefaultSources", "value": true}]'
      when: enable_disconnected
      register: catalog_sources
      until: catalog_sources is not failed
      retries: 50
      delay: 20

    - name: Template out nfs bits
      tags:
        - nfs
      ansible.builtin.template:
        src: "../templates/{{ item }}"
        dest: "{{ tempfolder }}/fullcluster/{{ item }}"
        mode: "0644"
      with_items:
        - nfs1.yaml
        - nfs2.yaml
        - nfs3.yaml
        
    - name: Install nfs
      tags:
        - nfs 
      ansible.builtin.shell: |
        set -e -o pipefail
        export KUBECONFIG="{{ tempfolder }}/fullcluster/auth/kubeconfig"
        "{{ mirrorfolder }}/{{ ocp_version }}"/oc apply -f "{{ tempfolder }}/fullcluster/nfs1.yaml"
        "{{ mirrorfolder }}/{{ ocp_version }}"/oc adm policy add-scc-to-user hostmount-anyuid system:serviceaccount:default:nfs-client-provisioner
        "{{ mirrorfolder }}/{{ ocp_version }}"/oc apply -f "{{ tempfolder }}/fullcluster/nfs2.yaml"
        "{{ mirrorfolder }}/{{ ocp_version }}"/oc apply -f "{{ tempfolder }}/fullcluster/nfs3.yaml"
      register: nfsstorage
      until: nfsstorage is not failed
      retries: 10
      delay: 20

    # - name: Template out localstorage bits
    #   tags:
    #     - localstorage
    #   ansible.builtin.template:
    #     src: "../templates/{{ item }}"
    #     dest: "{{ tempfolder }}/fullcluster/{{ item }}"
    #     mode: "0644"
    #   with_items:
    #     - local-storage-base.yaml
    #     - local-storage-cr.yaml
    #
    # - name: Install local storage operator
    #   tags:
    #     - localstorage
    #   ansible.builtin.shell: |
    #     set -e -o pipefail
    #     export KUBECONFIG="{{ tempfolder }}/fullcluster/auth/kubeconfig"
    #     "{{ mirrorfolder }}/{{ ocp_version }}"/oc apply -f "{{ tempfolder }}/fullcluster/local-storage-base.yaml"
    #   register: localstorage
    #   until: localstorage is not failed
    #   retries: 50
    #   delay: 20
    #
    # - name: Install local storage cr
    #   tags:
    #     - localstorage
    #   ansible.builtin.shell: |
    #     set -e -o pipefail
    #     export KUBECONFIG="{{ tempfolder }}/fullcluster/auth/kubeconfig"
    #     "{{ mirrorfolder }}/{{ ocp_version }}"/oc apply -f "{{ tempfolder }}/fullcluster/local-storage-cr.yaml"
    #     "{{ mirrorfolder }}/{{ ocp_version }}"/oc patch storageclass localfs-sc -p '{"metadata": {"annotations": {"storageclass.kubernetes.io/is-default-class": "true"}}}'
    #   register: localstorage
    #   until: localstorage is not failed
    #   retries: 5
    #   delay: 20

    # - name: Template out lvm bits
    #   tags:
    #     - lvm
    #   ansible.builtin.template:
    #     src: ../templates/lvm-base.yaml
    #     dest: "{{ tempfolder }}/fullcluster/lvm-base.yaml"
    #     mode: "0644"
    #
    # - name: Template out lvm cluster
    #   tags:
    #     - lvm
    #   ansible.builtin.template:
    #     src: ../templates/lvm-cluster.yaml
    #     dest: "{{ tempfolder }}/fullcluster/{{ item }}-lvm-cluster.yaml"
    #     mode: "0644"
    #   with_items:
    #     - worker-0
    #
    # - name: Install LVM operator
    #   tags:
    #     - lvm
    #   ansible.builtin.shell: |
    #     set -e -o pipefail
    #     export KUBECONFIG="{{ tempfolder }}/fullcluster/auth/kubeconfig"
    #     "{{ mirrorfolder }}/{{ ocp_version }}"/oc apply -f "{{ tempfolder }}/fullcluster/lvm-base.yaml"
    #   register: lvm
    #   until: lvm is not failed
    #   retries: 50
    #   delay: 20
    #
    # - name: Install LVM Cluster
    #   tags:
    #     - lvm
    #   ansible.builtin.shell: |
    #     set -e -o pipefail
    #     export KUBECONFIG="{{ tempfolder }}/fullcluster/auth/kubeconfig"
    #     "{{ mirrorfolder }}/{{ ocp_version }}"/oc apply -f "{{ tempfolder }}/fullcluster/{{ item }}-lvm-cluster.yaml"
    #   register: lvmcluster
    #   retries: 50
    #   delay: 30
    #   until: lvmcluster is not failed
    #   with_items:
    #     - worker-0

    - name: Set minio-s3 secret for image registry
      tags:
        - s3
      ansible.builtin.shell: |
        set -e
        export KUBECONFIG="{{ tempfolder }}/fullcluster/auth/kubeconfig";
        "{{ mirrorfolder }}/{{ ocp_version }}"/oc create secret generic image-registry-private-configuration-user \
              --from-literal=REGISTRY_STORAGE_S3_ACCESSKEY="{{ minio.admin_access_key }}" \
              --from-literal=REGISTRY_STORAGE_S3_SECRETKEY="{{ minio.admin_secret_key }}" --namespace openshift-image-registry
      register: miniosetup
      until: miniosetup is not failed
      retries: 3
      delay: 5

    - name: Set minio-s3 backend for image registry
      tags:
        - s3
      ansible.builtin.shell: |
        set -e
        export KUBECONFIG="{{ tempfolder }}/fullcluster/auth/kubeconfig";
        "{{ mirrorfolder }}/{{ ocp_version }}"/oc patch configs.imageregistry.operator.openshift.io cluster -n openshift-image-registry \
              --type merge --patch '{"spec": { "storage": { "s3": { "region": "notneeded", "regionEndpoint": "https://{{ minio.fqdn }}:{{ minio.port }}", "bucket": "{{ minio.bucket }}"}}}}'
        "{{ mirrorfolder }}/{{ ocp_version }}"/oc patch configs.imageregistry.operator.openshift.io cluster --type=json -p='[{"op": "add", "path": "/spec/managementState", "value": "Managed"}]'
      register: miniosetup
      until: miniosetup is not failed
      retries: 3
      delay: 5

    - name: Set kubeadmin password
      ansible.builtin.shell: |
        set -e -o pipefail
        PASS=$(python3 -c 'import bcrypt; print(bcrypt.hashpw(b"{{ kubeadmin_pass }}", bcrypt.gensalt(rounds=10)).decode())' | base64 -w0)
        export KUBECONFIG="{{ tempfolder }}/fullcluster/auth/kubeconfig"
        "{{ mirrorfolder }}/{{ ocp_version }}"/oc patch secret -n kube-system kubeadmin --type json \
          -p '[{"op": "replace", "path": "/data/kubeadmin", "value": "'$PASS'"}]'
      when: kubeadmin_pass is defined
      register: kubepass
      until: kubepass is not failed
      retries: 30
      delay: 5

    - name: Reset ca folder
      ansible.builtin.shell: |
        mkdir -p "{{ ca_folder }}"
        rm -f "{{ ca_folder }}/{{ item }}-ca-kube"
      with_items:
        - fullcluster

    - name: Does the firefox profile exist
      ansible.builtin.stat:
        path: "{{ firefox_profile }}"
      register: profile_path

    - name: Init firefox profile path
      ansible.builtin.shell: |
        mkdir -p "{{ firefox_profile }}"
      when: not profile_path.stat.exists

    # KUBECONFIG certificate-authority-data has the CA only for the API endpoint, we want all of them
    # /home/michele/Bin/yq '.clusters[0].cluster.certificate-authority-data' {{ item }}-kubeconfig | base64 -d > "{{ ca_folder }}/{{ item }}-ca-api"
    - name: Fetch all CAs for each cluster
      ansible.builtin.shell: |
        set -x -e -o pipefail
        export KUBECONFIG=/home/michele/{{ item }}-kubeconfig
        oc get -n default configmap/kube-root-ca.crt -o jsonpath="{.data.ca\.crt}" > "{{ ca_folder }}/{{ item }}-ca-kube"
      with_items:
        - fullcluster
      retries: 5
      delay: 10
      register: pki_import
      until: pki_import is not failed

    - name: Delete exiting CAs from SNOs
      ansible.builtin.shell: |
        set -e -o pipefail
        rm -f {{ ca_folder }}/{{ item }}-cert*pem
        awk 'BEGIN {c=0;} /BEGIN CERTIFICATE/ {c++} {print > "{{ item }}-cert" c ".pem"}' < {{ ca_folder }}/{{ item }}-ca-kube
        for i in {{ item }}-cert*; do
          certutil -D -n "{{ item }}-$i-kube" -d sql:"{{ firefox_profile }}" || true
        done
      args:
        chdir: "{{ ca_folder }}"
      with_items:
        - fullcluster
      retries: 5
      delay: 10
      register: pki_import
      until: pki_import is not failed

    - name: Import all CAs into my firefox profile
      ansible.builtin.shell: |
        set -e -o pipefail
        rm -f {{ ca_folder }}/cert*
        awk 'BEGIN {c=0;} /BEGIN CERTIFICATE/ {c++} {print > "{{ item }}-cert" c ".pem"}' < {{ ca_folder }}/{{ item }}-ca-kube
        for i in {{ item }}-cert*; do
          certutil -A -n "{{ item }}-$i-kube" -t "TC,C,C"  -i "$i" -d sql:"{{ firefox_profile }}"
        done
      args:
        chdir: "{{ ca_folder }}"
      with_items:
        - fullcluster
      retries: 10
      delay: 10
      register: pki_import
      until: pki_import is not failed
