---
- name: Mirror all needed container images locally
  hosts: kvm
  gather_facts: false
  become: true
  tasks:
    - name: Create mirror folders
      ansible.builtin.get_url:
        url: "{{ oc_mirror_url }}"
        dest: "/usr/local/bin/oc-mirror"
        mode: "0755"

    - name: Create folders
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      with_items:
        - "/root/.docker/"
        - "{{ local_mirror }}"
        - "{{ local_mirror }}/workspace"

    - name: Template pull secret
      ansible.builtin.template:
        dest: /root/.docker/config.json
        src: ../templates/pullsecret.json.j2
        mode: "0640"

    # The initial template was created via:
    # ./oc mirror init --registry {{ oc_mirror_local_registry }}/{{ item }} > imageset-config.yaml
    # See: https://docs.openshift.com/container-platform/4.14/installing/disconnected_install/installing-mirroring-disconnected.html
    - name: Create imageset-config
      ansible.builtin.template:
        src: ../templates/imageset-config.yaml
        dest: "{{ local_mirror }}/imageset-config.yaml"
        mode: "0644"

    - name: Mirror images
      ansible.builtin.shell: |
        set -e
        #mirror --config=/var/lib/libvirt/ocp-mirror/mirror/imageset-config.yaml  --workspace file://tmp/workspace docker://nas.int.rhx  --v2
        ./oc mirror --config={{ local_mirror }}/imageset-config.yaml --loglevel debug \
        --workspace file://{{ local_mirror }}/workspace docker://{{ oc_mirror_local_registry }} --v2 &> /var/log/oc-mirror.log
      args:
        chdir: "{{ mirrorfolder }}/{{ ocp_version }}"
