---
- name: Make sure registry has been restarted
  hosts: fw
  gather_facts: false
  become: true
  tasks:
    - name: Restart docker registry
      ansible.builtin.shell: |
        set -e -o pipefail
        ./docker-registry.sh
      args:
        chdir: /root/docker

- name: Mirror all needed container images locally
  hosts: kvm
  gather_facts: false
  become: true
  tasks:
    - name: Create mirror folders
      ansible.builtin.debug:
        msg: "Start"
