---
- name: Test operator upgrades
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  become_user: michele
  vars:
    vp_operator_tempfolder: "~/sno-vp-operator"
    gitrepo: https://github.com/validatedpatterns/patterns-operator
    upgrade_from: 0.0.45
    upgrade_to: main
    node: sno1
    from_version: 6.6.6
    to_version: 6.6.7
    registry: fw.int.rhx/bandini
    mcggitrepo: https://github.com/validatedpatterns/multicloud-gitops
    mcggitbranch: main
  tasks:
    - name: Print versions
      ansible.builtin.debug:
        msg: "Testing upgrade on {{ node }} from {{ upgrade_from }} to {{ upgrade_to }} of {{ gitrepo }}"

    - name: Check that all kubeconfig files exist
      ansible.builtin.stat:
        path: "~/{{ node }}-kubeconfig"
      register: kubeconfig_file

    - name: Verifying if file exists
      ansible.builtin.debug:
        msg: "Kubeconfig exists"
      failed_when: not kubeconfig_file.stat.exists

    - name: Delete temporary folder
      ansible.builtin.file:
        path: "{{ vp_operator_tempfolder }}"
        state: absent

    - name: Clone git repo
      ansible.builtin.git:
        repo: "{{ gitrepo }}"
        version: "{{ upgrade_from }}"
        dest: "{{ vp_operator_tempfolder }}/patterns-operator"
        clone: true
      tags:
        - operator-install

    - name: Build and upload operator version {{ upgrade_from }} - {{ from_version }}
      ansible.builtin.shell: |
        export KUBECONFIG=~/{{ node }}-kubeconfig
        make VERSION={{ from_version }} IMAGE_TAG_BASE={{ registry }}/patterns-operator \
            IMG={{ registry }}/patterns-operator:{{ from_version }} \
            CHANNELS=fast bundle generate docker-build docker-push bundle-build bundle-push catalog-build catalog-push catalog-install
      args:
        chdir: "{{ vp_operator_tempfolder }}/patterns-operator"
      tags:
        - operator-install

    - name: Wait for the catalog source to show up
      ansible.builtin.shell: |
        export KUBECONFIG=~/{{ node }}-kubeconfig
        oc get -n openshift-marketplace packagemanifests -l "catalog=test-pattern-operator" --field-selector "metadata.name=patterns-operator"
      retries: 20
      delay: 10
      register: catalogsource_ret
      until: catalogsource_ret is not failed
      tags:
        - operator-install

    - name: Install the subscription and operator
      ansible.builtin.shell: |
        set -e
        export KUBECONFIG=~/{{ node }}-kubeconfig
        cat > /tmp/vp-sub.yaml<<EOF
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: patterns-operator
          namespace: openshift-operators
          labels:
            operators.coreos.com/patterns-operator.openshift-operators: ""
        spec:
          channel: fast
          installPlanApproval: Automatic
          name: patterns-operator
          #source: community-operators
          source: test-pattern-operator
          sourceNamespace: openshift-marketplace
        EOF
        oc apply -f /tmp/vp-sub.yaml
      tags:
        - operator-install

    - name: Wait for the operator to be installed
      ansible.builtin.shell: |
        export KUBECONFIG=~/{{ node }}-kubeconfig
        oc get -n openshift-marketplace packagemanifests -l "catalog=test-pattern-operator" --field-selector "metadata.name=patterns-operator"  &> /dev/null
      retries: 20
      delay: 10
      register: operatorinstall_ret
      until: operatorinstall_ret is not failed
      tags:
        - operator-install

    - name: Install MCG pattern
      ansible.builtin.shell: |
        export KUBECONFIG=~/{{ node }}-kubeconfig
        cat > /tmp/vp-upgrade-pattern.yaml<<EOF
        apiVersion: gitops.hybrid-cloud-patterns.io/v1alpha1
        kind: Pattern
        metadata:
          name: multicloud-gitops
          namespace: openshift-operators
        spec:
          experimentalCapabilities: initcontainers
          clusterGroupName: hub
          multiSourceConfig:
            enabled: true
          gitSpec:
            targetRepo: {{ mcggitrepo }}
            targetRevision: {{ mcggitbranch }}
        EOF
        oc apply -f /tmp/vp-upgrade-pattern.yaml
      retries: 20
      delay: 10
      register: patterninstall_ret
      until: patterninstall_ret is not failed
      tags:
        - operator-install

    - name: Wait for clusterwide gitops
      ansible.builtin.shell: |
        set -e
        export KUBECONFIG=~/{{ node }}-kubeconfig
        oc get namespace/openshift-gitops
      retries: 50
      delay: 10
      register: clusterwide_gitops
      until: clusterwide_gitops is not failed
      tags:
        - operator-install

    - name: Reset git repo to upgraded version
      ansible.builtin.git:
        repo: "{{ gitrepo }}"
        version: "{{ upgrade_to }}"
        dest: "{{ vp_operator_tempfolder }}/patterns-operator"
        force: true
      tags:
        - operator-upgrade

    - name: Prepare catalog/template.yaml
      ansible.builtin.shell: |
        cat > catalog/template.yaml<<EOF
        schema: olm.package
        name: patterns-operator
        defaultChannel: fast
        ---
        schema: olm.channel
        package: patterns-operator
        name: fast
        entries:
        - name: patterns-operator.v{{ from_version }}
        - name: patterns-operator.v\$VERSION
          replaces: patterns-operator.v{{ from_version }}
        ---
        schema: olm.bundle
        image: fw.int.rhx/bandini/patterns-operator-bundle:v{{ from_version }}
        ---
        schema: olm.bundle
        image: \$BUNDLE_IMG
        EOF
      args:
        chdir: "{{ vp_operator_tempfolder }}/patterns-operator"
      tags:
        - operator-upgrade

    - name: Build and upload upgraded operator version {{ upgrade_to }} - {{ to_version }}
      ansible.builtin.shell: |
        export KUBECONFIG=~/{{ node }}-kubeconfig
        make VERSION={{ to_version }} IMAGE_TAG_BASE={{ registry }}/patterns-operator \
            IMG={{ registry }}/patterns-operator:{{ to_version }} \
            CHANNELS=fast bundle generate docker-build docker-push bundle-build bundle-push catalog-build catalog-push catalog-install
      args:
        chdir: "{{ vp_operator_tempfolder }}/patterns-operator"
      tags:
        - operator-upgrade
