---
- name: Restart docker-caches
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Restart cache and registry
      ansible.builtin.shell: |
        set -e -o pipefail
        ./docker-cache.sh
        ./docker-registry.sh
      args:
        chdir: /home/michele/docker

- name: Install SNO clusters
  hosts: "{{ snos | default('snohosts') }}"
  gather_facts: false
  become: true
  strategy: ansible.builtin.free
  roles:
    - sno_install
