---
- name: Destroy SNO cluser
  hosts: kvm
  gather_facts: false
  become: true
  tasks:
    - name: Check if vms already exists
      community.libvirt.virt:
        command: list_vms
      register: all_vms

    - name: Destroy {{ item }}
      ansible.builtin.shell: |
        virsh destroy {{ item }}
        virsh undefine --remove-all-storage {{ item }}
      when: 'item in all_vms.list_vms'
      with_items: "{{ snos }}"

    - name: Remove tempfolder
      ansible.builtin.file:
        path: "{{ tempfolder }}"
        state: absent
