---
- name: Install Connected Vehicle on sno1
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  become_user: michele
  vars:
    vehicletempfolder: "~/sno-connected-vehicle"
    gitrepo: https://github.com/validatedpatterns/connected-vehicle-architecture
    gitbranch: main
    node: sno1
  tasks:
    - name: Check that all kubeconfig files exist {{ node }}
      ansible.builtin.stat:
        path: "~/{{ node }}-kubeconfig"
      register: kubeconfig_files

    - name: Verifying if files exists
      ansible.builtin.debug:
        msg: "File exist"
      failed_when: not kubeconfig_files.stat.exists

    - name: Delete temporary folder
      ansible.builtin.file:
        path: "{{ vehicletempfolder }}"
        state: absent

    - name: Create temporary folder
      ansible.builtin.file:
        path: "{{ vehicletempfolder }}/connected-vehicle-architecture"
        state: directory
        recurse: true

    - name: Clone git repo
      ansible.builtin.git:
        repo: "{{ gitrepo }}"
        dest: "{{ vehicletempfolder }}/connected-vehicle-architecture"
        version: "{{ gitbranch }}"
        clone: true

    - name: Install pattern on HUB/sno1
      ansible.builtin.shell: |
        set -e -o pipefail
        export KUBECONFIG=~/{{ node }}-kubeconfig
        ./pattern.sh make install &> /tmp/connected1.log
      args:
        chdir: "{{ vehicletempfolder }}/connected-vehicle-architecture"

    - name: Wait for all argo apps to be green
      ansible.builtin.shell: |
        set -e -o pipefail
        export KUBECONFIG=~/{{ node }}-kubeconfig
        make argo-healthcheck
      args:
        chdir: "{{ vehicletempfolder }}/connected-vehicle-architecture"
      retries: 30
      delay: 20
      register: argo
      until: argo is not failed
