---
- name: Install ArgoCD from git on sno1
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  become_user: michele
  vars:
    argotempfolder: "/tmp/argocd-git/"
    argorepo: https://github.com/argoproj/argo-cd/
    node: sno1
    quay_user: rhn_support_mbaldess
    quay_pass_field: quay.io
  tasks:
    - name: Check that all kubeconfig files exist
      ansible.builtin.stat:
        path: "~/{{ item }}-kubeconfig"
      with_items: "{{ snos | intersect(node) }}"
      register: kubeconfig_files

    - name: Verifying if files exists
      ansible.builtin.debug:
        msg: "File {{ item.stat.path }} exist"
      loop: "{{ kubeconfig_files.results }}"
      loop_control:
        label: "{{ item.stat.path }}"
      failed_when: not item.stat.exists

    - name: Try and log in to podman
      ansible.builtin.shell: |
        set -e -o pipefail
        echo $(pass show {{ quay_pass_field }} | head -n1) | podman login -u{{ quay_user }} quay.io --password-stdin

    - name: Create temporary folder
      ansible.builtin.file:
        path: "{{ argotempfolder }}/argo-cd"
        state: directory
        recurse: true

    - name: Clone git repo
      ansible.builtin.git:
        repo: "{{ argorepo }}"
        dest: "{{ argotempfolder }}/argo-cd"
        clone: true
        force: true

    - name: Patch argo for podman
      ansible.builtin.shell: |
        set -e -o pipefail
        git reset --hard
        git clean -dxf
        curl -o /tmp/argo.patch -L https://gist.githubusercontent.com/mbaldessari/e1eff9aba4e053b908bd103c749e705b/raw/6c200f33d2e06ed074b65abda2caa63ce919523e/argo.patch
        git apply /tmp/argo.patch
      args:
        chdir: "{{ argotempfolder }}/argo-cd"

    - name: Build and push the newly built container
      ansible.builtin.shell: |
        set -e -o pipefail
        make DOCKER_PUSH=true IMAGE_NAMESPACE=quay.io/rhn_support_mbaldess \
          DOCKER_RUN_OPTIONAL_ARGS="--userns=keep-id --security-opt label=disable" all &> build.log
      args:
        chdir: "{{ argotempfolder }}/argo-cd"

    - name: Tweak manifests for installation
      ansible.builtin.shell: |
        set -e -o pipefail
        make DOCKER_PUSH=true IMAGE_NAMESPACE=quay.io/rhn_support_mbaldess \
          DOCKER_RUN_OPTIONAL_ARGS="--userns=keep-id --security-opt label=disable" manifests &> manifest.log
        # Silly redis default breaks on OCP
        sed -i -e "/runAsUser: 999/d" manifests/install.yaml
      args:
        chdir: "{{ argotempfolder }}/argo-cd"

    - name: Create argocd project
      ansible.builtin.shell: |
        export KUBECONFIG=~/{{ node }}-kubeconfig
        oc new-project argocd

    - name: Install argo manifest
      ansible.builtin.shell: |
        export KUBECONFIG=~/{{ node }}-kubeconfig
        oc apply -f manifests/install.yaml
      args:
        chdir: "{{ argotempfolder }}/argo-cd"

    - name: Template out argo route
      ansible.builtin.template:
        src: ../templates/argo-route.yaml
        dest: "{{ argotempfolder }}/argo-cd/argo-route.yaml"
        mode: "0644"

    - name: Install argo route
      ansible.builtin.shell: |
        export KUBECONFIG=~/{{ node }}-kubeconfig
        oc apply -f argo-route.yaml
      args:
        chdir: "{{ argotempfolder }}/argo-cd"
      retries: 5
      delay: 10
      register: route
      until: route is not failed

    - name: Get argo secret
      ansible.builtin.shell: |
        export KUBECONFIG=~/{{ node }}-kubeconfig
        oc extract -n argocd secrets/argocd-initial-admin-secret --to=- 2>/dev/null
      args:
        chdir: "{{ argotempfolder }}/argo-cd"
      register: argosecret

    - name: Print secret
      ansible.builtin.debug:
        msg: "ARGO ADMIN PASSWORD: {{ argosecret.stdout }}"
