---
- name: Install MCG on the three clusters
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  become_user: michele
  vars:
    mcgtempfolder: "~/sno-mcg"
    gitrepo: https://github.com/validatedpatterns/multicloud-gitops
  tasks:
    - name: Check that all kubeconfig files exist
      ansible.builtin.stat:
        path: "~/{{ item }}-kubeconfig"
      with_items: "{{ snos }}"

    - name: Delete temporary folder
      ansible.builtin.file:
        path: "{{ mcgtempfolder }}"
        state: absent

    - name: Create temporary folder
      ansible.builtin.file:
        path: "{{ mcgtempfolder }}/multicloud-gitops"
        state: directory
        recurse: true

    - name: Clone git repo
      ansible.builtin.git:
        repo: "{{ gitrepo }}"
        dest: "{{ mcgtempfolder }}/multicloud-gitops"
        clone: true

    - name: Install pattern on HUB/sno1
      ansible.builtin.shell: |
        set -e -o pipefail
        export KUBECONFIG=~/sno1-kubeconfig
        ./pattern.sh make install
      args:
        chdir: "{{ mcgtempfolder }}/multicloud-gitops"

    - name: Wait for all argo apps to be green
      tags:
        - zozzo
      ansible.builtin.shell: |
        set -e -o pipefail
        export KUBECONFIG=~/sno1-kubeconfig
        APPS=$(oc get applications -A -o jsonpath='{range .items[*]}{@.metadata.namespace}{","}{@.metadata.name}{"\n"}{end}')
        NOTSYNCED=0
        for i in $APPS; do
          NS=$(echo "${i}" | cut -f1 -d,)
          APP=$(echo "${i}" | cut -f2 -d,)
          STATUS=$(oc get -n "${NS}" application/"${APP}" -o jsonpath='{.status.sync.status}')
          if [ $STATUS != "Syncedd" ]; then
            NOTSYNCED=$((NOTSYNCED + 1))
          fi
          echo "${NS} ${APP} -> ${STATUS}"
        done
        if [ $NOTSYNCED -gt 0 ]; then
           echo "Applications not synced: ${NOTSYNCED}"
           exit 1
        fi
      args:
        chdir: "{{ mcgtempfolder }}/multicloud-gitops"
      retries: 100
      delay: 20
      register: argo
      until: argo is not failed
