---
- name: Prepare SNO clusters
  hosts: kvm
  gather_facts: false
  become: true
  tasks:
    - name: Create temporary folders
      ansible.builtin.file:
        path: "{{ tempfolder }}/{{ item }}"
        state: directory
        recurse: true
      with_items: "{{ snos }}"

    - name: Check if oc already exists
      ansible.builtin.stat:
        path: "{{ tempfolder }}/oc"
      register: oc_binary

    - name: Check if openshift-install already exists
      ansible.builtin.stat:
        path: "{{ tempfolder }}/openshift-install"
      register: openshift_install_binary

    - name: Download oc
      ansible.builtin.get_url:
        url: "{{ openshift_mirror }}/{{ ocp_version }}/openshift-client-linux.tar.gz"
        dest: "{{ tempfolder }}/openshift-client-linux.tar.gz"
        mode: "0640"
      environment:
        https_proxy: "{{ https_proxy | default('') }}"
      when: not oc_binary.stat.exists

    - name: Download openshift-install
      ansible.builtin.get_url:
        url: "{{ openshift_mirror }}/{{ ocp_version }}/openshift-install-linux.tar.gz"
        dest: "{{ tempfolder }}/openshift-install-linux.tar.gz"
        mode: "0640"
      environment:
        https_proxy: "{{ https_proxy | default('') }}"
      when: not openshift_install_binary.stat.exists

    - name: Uncompress oc
      ansible.builtin.unarchive:
        src: "{{ tempfolder }}/openshift-client-linux.tar.gz"
        dest: "{{ tempfolder }}"
        remote_src: true
      when: not oc_binary.stat.exists

    - name: Uncompress openshift install
      ansible.builtin.unarchive:
        src: "{{ tempfolder }}/openshift-install-linux.tar.gz"
        dest: "{{ tempfolder }}"
        remote_src: true
      when: not openshift_install_binary.stat.exists

    - name: Register iso URL
      ansible.builtin.shell: |
        set -e -o pipefail
        ./openshift-install coreos print-stream-json | grep location | grep "{{ arch }}" | grep iso | cut -d\" -f4
      args:
        chdir: "{{ tempfolder }}"
      register: iso_url_raw

    - name: Download RHCOS iso
      ansible.builtin.get_url:
        url: "{{ iso_url_raw.stdout }}"
        dest: "{{ tempfolder }}/rhcos-live.iso"
        mode: "0664"
        validate_certs: false
      environment:
        https_proxy: "{{ https_proxy | default('') }}"

- name: Prepare Docker cache registry
  hosts: fw
  gather_facts: false
  become: true
  tasks:
    - name: Restart docker caches
      ansible.builtin.shell: |
        set -e -o pipefail
        ./docker-cache.sh
      args:
        chdir: /root/docker
