---
- name: Install MCG on the three clusters
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  become_user: michele
  vars:
    mcgtempfolder: "~/sno-mcg"
    hub: sno1
    spoke: sno2
    pipfolder: "~/pip-mcg"
  tasks:
    - name: Check that all kubeconfig files exist
      ansible.builtin.stat:
        path: "~/{{ item }}-kubeconfig"
      with_items:
        - "{{ hub }}"
        - "{{ spoke }}"
      register: kubeconfig_files

    - name: Verifying if files exists
      ansible.builtin.debug:
        msg: "File {{ item.stat.path }} exist"
      loop: "{{ kubeconfig_files.results }}"
      loop_control:
        label: "{{ item.stat.path }}"
      failed_when: not item.stat.exists

    - name: Load values-global.yaml from pattern
      ansible.builtin.include_vars:
        file: "{{ mcgtempfolder }}/multicloud-gitops/values-global.yaml"
        name: pattern_values

    - name: Set up pip environment
      ansible.builtin.shell: |
        set -e -o pipefail
        rm -rf "{{ pipfolder | expanduser }}"
        mkdir -p "{{ pipfolder }}"
        python3 -m virtualenv "{{ pipfolder }}"
        source "{{ pipfolder }}/bin/activate"
        pip install -r requirements.txt > /tmp/pip-mcg-install.log
      args:
        chdir: "{{ mcgtempfolder }}/multicloud-gitops/tests/interop"
      

    - name: Run qe tests
      ansible.builtin.shell: |
        set -e -o pipefail
        export KUBECONFIG=~/{{ hub }}-kubeconfig
        export KUBECONFIG_EDGE=~/{{ spoke }}-kubeconfig
        export WORKSPACE=/tmp/mcg-workspace
        export INFRA_PROVIDER=baremetal
        export SKIP_GIT_CHANGES=true
        export SKIP_CI_BADGE=true
        source "{{ pipfolder }}/bin/activate"
        ./run_tests.sh &> /tmp/mcg-qe-run-tests.log
      args:
        chdir: "{{ mcgtempfolder }}/multicloud-gitops/tests/interop"

