---
- name: Install MCG using an IIB for gitops
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  become_user: michele
  vars:
    mcgtempfolder: "~/sno-mcg"
    gitrepo: https://github.com/validatedpatterns/multicloud-gitops
    gitbranch: main
    hub: sno1
  tasks:
    - name: Fail if iib is not defined
      ansible.builtin.fail:
        msg: "IIB is not defined"
      when: iib is not defined or iib == ""

    - name: Check that all kubeconfig files exist
      ansible.builtin.stat:
        path: "~/{{ item }}-kubeconfig"
      with_items: 
        - "{{ hub }}"
      register: kubeconfig_files

    - name: Verifying if files exists
      ansible.builtin.debug:
        msg: "File {{ item.stat.path }} exist"
      loop: "{{ kubeconfig_files.results }}"
      loop_control:
        label: "{{ item.stat.path }}"
      failed_when: not item.stat.exists

    - name: Enable SNO internal registry
      ansible.builtin.shell: |
        set -e
        export KUBECONFIG=~/{{ hub }}-kubeconfig
        oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"managementState":"Managed"}}'
        oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"storage":{"emptyDir":{}}}}'

    - name: Delete temporary folder
      ansible.builtin.file:
        path: "{{ mcgtempfolder }}"
        state: absent

    - name: Create temporary folder
      ansible.builtin.file:
        path: "{{ mcgtempfolder }}/multicloud-gitops"
        state: directory
        recurse: true

    - name: Clone git repo
      ansible.builtin.git:
        repo: "{{ gitrepo }}"
        version: "{{ gitbranch }}"
        dest: "{{ mcgtempfolder }}/multicloud-gitops"
        clone: true

    - name: Load IIB "{{ iib }}"
      ansible.builtin.shell: |
        set -e
        export KUBECONFIG=~/{{ hub }}-kubeconfig
        make load-iib &> /tmp/iib-ansible-{{ hub }}.log
      environment:
        KUBEADMINPASS: "{{ kubeadmin_pass }}"
        OPERATOR: openshift-gitops-operator
        IIB: "{{ iib }}"
        INDEX_IMAGES: "{{ iib_index_image_base }}/iib:{{ iib }}"
      args:
        chdir: "{{ mcgtempfolder }}/multicloud-gitops"

    - name: Install pattern on HUB/{{ hub }}
      ansible.builtin.shell: |
        set -e -o pipefail
        export KUBECONFIG=~/{{ hub }}-kubeconfig
        export CHANNEL=$(oc get -n openshift-marketplace packagemanifests -l "catalog=iib-${IIB}" --field-selector "metadata.name=${OPERATOR}" -o jsonpath='{.items[0].status.defaultChannel}')
        make EXTRA_HELM_OPTS="--set main.gitops.operatorSource=iib-${IIB} --set main.gitops.channel=${CHANNEL}" install
      environment:
        KUBEADMINPASS: "{{ kubeadmin_pass }}"
        OPERATOR: openshift-gitops-operator
        IIB: "{{ iib }}"
        INDEX_IMAGES: "{{ iib_index_image_base }}/iib:{{ iib }}"
      args:
        chdir: "{{ mcgtempfolder }}/multicloud-gitops"
